name: mandrake
description: The Animagus GUI.

publish_to: 'none'
version: 0.1.3+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  basic_utils: ^2.5.3
  convert: ^2.1.1
  cupertino_icons: ^0.1.3
  json_annotation: ^3.0.1
  path: ^1.7.0
  protobuf: ^1.0.1
  provider: ^4.0.5
  shared_preferences: ^0.5.8
  string_validator: ^0.1.4
  truncate: ^2.1.2
  undo: ^1.2.0+2
  universal_io: ^1.0.1
  url_launcher: ^5.7.0
  url_launcher_platform_interface: 1.0.8
  uuid: ^2.0.4

  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 64ce78da00a050f5eebfad0de5f0adf491ae5a98
  menubar:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
      ref: 6e3aad1e75b27ae12ff11407bdfab1d85cdbb52c

dev_dependencies:
  build_runner: 1.10.1
  flutter_test:
    sdk: flutter
  json_serializable: ^3.4.1
  pedantic: ^1.9.0

dependency_overrides:
  build_resolvers: 1.3.10
  analyzer: 0.39.14

flutter:
  uses-material-design: true
