name: Mandrake web deploy

on:
  push:
    branches: [develop]

jobs:
  deploy:
    name: Deploy web
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - name: Enable web
      run: flutter config --enable-web
    - name: Install Dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter test
    - name: Build web
      run: flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        FOLDER: build/web
        ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
