name: Mandrake CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'
    - name: Install Dependencies
      run: flutter pub get
    - name: Lint
      run: flutter analyze
    - name: Run tests
      run: flutter test
