name: Mandrake CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'
    - name: Install Dependencies
      run: flutter pub get
    - name: Lint
      run: flutter analyze
    - name: Run tests
      run: flutter test --test-randomize-ordering-seed random
    - name: Build web
      run: flutter build web  --release --dart-define=FLUTTER_WEB_USE_SKIA=true
    - name: Deploy web
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        REPOSITORY_NAME: ashchan/mandrake-preview
        ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
        BRANCH: master
        TARGET_FOLDER: docs
        FOLDER: build/web
